name: cel_bridge_flutter_example
description: A cross-platform CEL workbench example.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cel_bridge:
    path: ../..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

hooks:
  user_defines:
    cel_bridge:
      build_from_source: true

flutter:
  uses-material-design: true
