name: cel_bridge_dart_cli_example
description: A small command-line example for cel_bridge.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  cel_bridge:
    path: ../..

hooks:
  user_defines:
    cel_bridge:
      build_from_source: true
